version: "3.8"

services:
  categories_service_mysql:
    build:
      context: ./database/mysql
      dockerfile: Dockerfile
    image: categories_service_mysql:v1
    container_name: categories_service_mysql_container
    env_file:
      - ./database/mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - categories_service_mysql_data:/var/lib/mysql
    networks:
      app_network:
        ipv4_address: 192.168.0.120  # MySQL IP

  categories_service_php:
    build:
      context: ./web/php
      dockerfile: Dockerfile
    image: categories_service_php:v1
    container_name: categories_service_php_container
    working_dir: /var/www/html/x2microservices-categories-service
    env_file:
      - ./web/php/.env
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./web/php:/var/www/html/x2microservices-categories-service
      - ./web/php/vendor:/var/www/html/x2microservices-categories-service/vendor
    depends_on:
      - categories_service_mysql
    networks:
      app_network:
        ipv4_address: 192.168.0.121  # PHP IP

  nginx:
    build:
      context: ./web/nginx
      dockerfile: Dockerfile
    image: categories_service_nginx:v1
    container_name: categories_service_nginx_container
    working_dir: /var/www/html/x2microservices-categories-service
    env_file:
      - ./web/nginx/.env
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - categories_service_php
    networks:
      app_network:
        ipv4_address: 192.168.0.122  # Nginx IP

volumes:
  categories_service_mysql_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"
    external: false
